console.error('vectorize:export no longer reads Vectorize or writes embeddings_2d.json.')
console.error('Prepare a local vectors JSON file, then run:')
console.error('npm run explorer:export --workspace=@mtl-archives/scripts -- --input vectors.json --out ./tmp/explorer-artifacts --dry-run')
console.error('Production steps are in docs/explorer-modernization.md. This command does not upload artifacts.')
process.exit(1)
