import type { ScheduledController, ExecutionContext } from "@cloudflare/workers-types";
// @ts-ignore OpenNext generates this module during build.
import handler from "./.open-next/worker.js";
// @ts-ignore Generated by OpenNext during build.
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";
export default {
  async fetch(request: Request, env: CloudflareEnv, ctx: ExecutionContext) {
    const url = new URL(request.url);
    if (url.hostname === 'subscribe.mtlarchives.com') {
      return Response.redirect('https://www.mtlarchives.com/#newsletter', 308);
    }
    if (url.hostname === 'mtlarchives.com') {
      url.hostname = 'www.mtlarchives.com';
      return Response.redirect(url.toString(), 307);
    }
    // Public same-origin API proxies stay on the existing API Worker. Local Next
    // handlers (payments, images and research orchestration) keep their routes.
    if (["/api/photos", "/api/search", "/api/map", "/api/thumb", "/api/sitemap", "/api/newsletter/subscribe"].includes(url.pathname)) {
      url.hostname = "api.mtlarchives.com";
      return env.ARCHIVE_API.fetch(new Request(url, request));
    }
    if (request.method === 'GET' || request.method === 'HEAD') {
      const asset = await env.ASSETS.fetch(request);
      if (asset.status !== 404) return asset;
    }
    return handler.fetch(request, env, ctx);
  },
  async scheduled(_event: ScheduledController, env: CloudflareEnv, ctx: ExecutionContext) {
    ctx.waitUntil((async () => {
      const response = await env.WORKER_SELF_REFERENCE!.fetch(
        "https://www.mtlarchives.com/api/cron/newsletter",
        { headers: { authorization: `Bearer ${env.CRON_SECRET}` } },
      );
      if (!response.ok) throw new Error(`Newsletter trigger failed: ${response.status}`);
    })());
  },
};
