import type { ScheduledController, ExecutionContext } from "@cloudflare/workers-types";
// @ts-ignore OpenNext generates this module during build.
import handler from "./.open-next/worker.js";
// @ts-ignore Generated by OpenNext during build.
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";
export default {
  fetch(request: Request, env: CloudflareEnv, ctx: ExecutionContext) {
    const url = new URL(request.url);
    if (url.hostname === 'subscribe.mtlarchives.com') {
      return Response.redirect('https://www.mtlarchives.com/#newsletter', 308);
    }
    if (url.hostname === 'mtlarchives.com') {
      url.hostname = 'www.mtlarchives.com';
      return Response.redirect(url.toString(), 307);
    }
    return handler.fetch(request, env, ctx);
  },
  async scheduled(_event: ScheduledController, env: CloudflareEnv, ctx: ExecutionContext) {
    ctx.waitUntil((async () => {
      const response = await env.WORKER_SELF_REFERENCE!.fetch(
        "https://www.mtlarchives.com/api/cron/newsletter",
        { headers: { authorization: `Bearer ${env.CRON_SECRET}` } },
      );
      if (!response.ok) throw new Error(`Newsletter trigger failed: ${response.status}`);
    })());
  },
};
