import type { Metadata, Viewport } from "next";
import { Figtree, Spectral, Manrope, IBM_Plex_Mono } from "next/font/google";
import { AnalyticsProvider } from "@/components/AnalyticsProvider";
import "./globals.css";
import { CartProvider } from "@/lib/cart-context";
import { CartDrawer } from "@/components/CartDrawer";
import { FlagValues } from "@/components/FlagValues";
import { API_ORIGIN, R2_ORIGIN } from "@/lib/runtime-config";

const figtree = Figtree({
  subsets: ['latin'],
  variable: '--font-sans',
  display: 'swap',
});

const spectral = Spectral({
  subsets: ['latin'],
  variable: '--font-display',
  weight: ['400', '600', '700'],
  display: 'swap',
});

const manrope = Manrope({
  subsets: ['latin'],
  variable: '--font-brand',
  display: 'swap',
});

const ibmPlexMono = IBM_Plex_Mono({
  subsets: ['latin'],
  variable: '--font-mono',
  weight: ['400', '500'],
  display: 'swap',
});

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://www.mtlarchives.com';

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
  userScalable: true,
  viewportFit: 'cover',
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#F5F2EA' },
    { media: '(prefers-color-scheme: dark)', color: '#111318' },
  ],
};

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: 'MTL Archives — Photos historiques de Montréal',
    template: '%s | MTL Archives',
  },
  description: 'Explorez 14 822 photos historiques de Montréal. Recherchez par rue, quartier ou lieu emblématique. Explore 14,822 historical photos of Montreal.',
  keywords: [
    'Montreal', 'Montréal', 'archives', 'photos', 'historical', 'historique',
    'history', 'histoire', 'Quebec', 'Québec', 'vintage', 'old photos',
    'Vieux-Montréal', 'Old Montreal', 'patrimoine', 'heritage'
  ],
  authors: [{ name: 'MTL Archives' }],
  creator: 'MTL Archives',
  publisher: 'MTL Archives',
  
  // Open Graph - images are auto-generated by opengraph-image.tsx
  openGraph: {
    type: 'website',
    locale: 'fr_CA',
    alternateLocale: 'en_CA',
    url: siteUrl,
    siteName: 'MTL Archives',
    title: 'MTL Archives — Photos historiques de Montréal',
    description: 'Explorez 14 822 photos historiques de Montréal. Recherchez par rue, quartier ou lieu emblématique.',
    // Images auto-generated by opengraph-image.tsx (1200x630)
  },
  
  // Twitter Card - images are auto-generated by twitter-image.tsx
  twitter: {
    card: 'summary_large_image',
    site: '@mtlarchives',
    creator: '@mtlarchives',
    title: 'MTL Archives — Photos historiques de Montréal',
    description: 'Explorez 14 822 photos historiques de Montréal.',
    // Images auto-generated by twitter-image.tsx (1200x630)
  },
  
  // Additional meta for broader platform support
  other: {
    'apple-mobile-web-app-title': 'MTL Archives',
    'application-name': 'MTL Archives',
    'msapplication-TileColor': '#111318',
    'theme-color': '#F5F2EA',
  },
  
  // Icons - using Next.js generated icons
  // icon.tsx, apple-icon.tsx handle dynamic generation
  
  // App configuration
  appleWebApp: {
    capable: true,
    statusBarStyle: 'default',
    title: 'MTL Archives',
  },
  
  // Other
  formatDetection: {
    telephone: false,
  },
  
  // Robots
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  
  // Verification (add your IDs when ready)
  // verification: {
  //   google: 'your-google-verification-code',
  // },

};

// Organization JSON-LD for homepage
const organizationJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'Organization',
  name: 'MTL Archives',
  url: siteUrl,
  logo: `${siteUrl}/icon-512.png`,
  description: 'Explorez 14 822 photos historiques de Montréal. Recherchez par rue, quartier ou lieu emblématique.',
  sameAs: [
    'https://twitter.com/mtlarchives',
  ],
};

// CollectionPage JSON-LD for the photo archive
const collectionJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'CollectionPage',
  name: 'MTL Archives — Photos historiques de Montréal',
  description: 'Collection de 14 822 photos historiques des archives de la Ville de Montréal.',
  url: siteUrl,
  publisher: {
    '@type': 'Organization',
    name: 'Archives de la Ville de Montréal',
  },
  about: {
    '@type': 'Place',
    name: 'Montréal, Québec, Canada',
  },
  inLanguage: ['fr-CA', 'en-CA'],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className={`${figtree.variable} ${spectral.variable} ${manrope.variable} ${ibmPlexMono.variable}`}>
      <head>
        {/* Preconnect to API for faster initial fetch */}
        {API_ORIGIN ? (
          <>
            <link rel="preconnect" href={API_ORIGIN} />
            <link rel="dns-prefetch" href={API_ORIGIN} />
          </>
        ) : null}
        {/* Preconnect to R2 for faster image loads */}
        {R2_ORIGIN ? (
          <>
            <link rel="preconnect" href={R2_ORIGIN} />
            <link rel="dns-prefetch" href={R2_ORIGIN} />
          </>
        ) : null}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(organizationJsonLd),
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(collectionJsonLd),
          }}
        />
      </head>
      <body className="font-sans antialiased bg-background text-foreground min-h-screen">
        <CartProvider>
          {children}
          <CartDrawer />
        </CartProvider>
        <FlagValues />
        <AnalyticsProvider />
      </body>
    </html>
  );
}
